# Generated by Django 5.0.9 on 2024-11-21 13:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('JogoID', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(blank=True, max_length=255, null=True)),
                ('CategoriaID', models.IntegerField(blank=True, null=True)),
                ('Ordem', models.IntegerField(blank=True, null=True)),
                ('ExibirHome', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tblJogos',
            },
        ),
        migrations.CreateModel(
            name='ImagemJogo',
            fields=[
                ('ImagemJogoID', models.AutoField(primary_key=True, serialize=False)),
                ('ImgIndex', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ImgIndex')),
                ('ImgPaginaJogo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ImgPaginaJogo')),
                ('ImgNoticia1', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ImgNoticia1')),
                ('ImgNoticia2', cloudinary.models.CloudinaryField(max_length=255, verbose_name='ImgNoticia2')),
                ('JogoID', models.ForeignKey(db_column='JogoID', on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='games.jogo')),
            ],
            options={
                'db_table': 'tblImagensJogos',
            },
        ),
    ]
