# Generated by Django 5.0.9 on 2024-11-21 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('CategoriaID', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'tblCategorias',
            },
        ),
        migrations.AlterField(
            model_name='jogo',
            name='Nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='Ordem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='CategoriaID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.categoria'),
        ),
    ]
