# Generated by Django 5.0.9 on 2024-11-21 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_categoria_alter_jogo_nome_alter_jogo_ordem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaginaJogo',
            fields=[
                ('PaginaJogoID', models.AutoField(primary_key=True, serialize=False)),
                ('ResumoJogo', models.TextField(blank=True, null=True)),
                ('LinkDownload', models.CharField(blank=True, max_length=255, null=True)),
                ('DescricaoJogo', models.CharField(blank=True, max_length=255, null=True)),
                ('TituloTutorial', models.TextField(blank=True, null=True)),
                ('DescricaoTutorial', models.CharField(blank=True, max_length=255, null=True)),
                ('TituloNoticia1', models.TextField(blank=True, null=True)),
                ('DescricaoNoticia1', models.CharField(blank=True, max_length=255, null=True)),
                ('TituloNoticia2', models.TextField(blank=True, null=True)),
                ('DescricaoNoticia2', models.CharField(blank=True, max_length=255, null=True)),
                ('TituloVideo', models.CharField(blank=True, max_length=255, null=True)),
                ('DescricaoVideo', models.TextField(blank=True, null=True)),
                ('LinkVideo', models.CharField(blank=True, max_length=255, null=True)),
                ('JogoID', models.ForeignKey(db_column='JogoID', on_delete=django.db.models.deletion.CASCADE, related_name='pagina', to='games.jogo')),
            ],
            options={
                'db_table': 'tblPaginaJogos',
            },
        ),
        migrations.CreateModel(
            name='TutorialJogo',
            fields=[
                ('TutorialJogoid', models.AutoField(primary_key=True, serialize=False)),
                ('Ordem', models.IntegerField(null=True)),
                ('Passo', models.CharField(blank=True, max_length=255, null=True)),
                ('DescricaoPasso', models.TextField(blank=True, null=True)),
                ('JogoID', models.ForeignKey(db_column='JogoID', on_delete=django.db.models.deletion.CASCADE, related_name='tutorial', to='games.jogo')),
            ],
            options={
                'db_table': 'tblTutorialJogos',
            },
        ),
    ]
