# Generated by Django 5.0.9 on 2024-11-22 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_paginajogo_tutorialjogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paginajogo',
            name='DescricaoJogo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paginajogo',
            name='DescricaoNoticia1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paginajogo',
            name='DescricaoNoticia2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paginajogo',
            name='DescricaoTutorial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paginajogo',
            name='TituloNoticia1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paginajogo',
            name='TituloNoticia2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paginajogo',
            name='TituloTutorial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
